### PR TITLE
cross compiller type name template

### PR DESCRIPTION
**Pull request by KostinPavel**
Problem:
using magic constant for prefix and suffix in template function type_name ().

Solution:
constexpr auto detect magic numbers for prefix and suffix

### CODE REVIEW

**Comment by KostinPavel** [comment]
I don't have windows compilers. So I don't understand what the problem is.
Let me know if you are interested to continue.

**Comment by krzysztof-jusiak** [comment]
> I don't have windows compilers. So I don't understand what the problem is. Let me know if you are interested to continue.

Hi @KostinPavel, I think that would be a great addition, so encourage to carry on. I personally don't have windows compiler either but usually testing via godbolt msvc compilers (just copy past the whole code or include <http...> which is supported by compiler explorer and play with it like that)

**Comment by KostinPavel** [comment]
Now I used the old way for MSVC. I think MSVC users will find a solution later.

**Comment by krzysztof-jusiak** [comment]
that's okay, can we just enable the tests for clang/gcc and cleanup the comments please and we good to go, thansk

**Comment by KostinPavel** [comment]
Good. I'm using your recommendations to make the code better.

**Comment by KostinPavel** [comment]
The keyword "struct" was not included in the new method in the reference value for the search. Although this feature was indicated in the tests as a feature of the MSVC compiler.

**Comment by KostinPavel** [comment]
Now it works with all compilers used in the test.
Please check the possibility of using it in the project.

**Comment by krzysztof-jusiak** [comment]
Very nice @KostinPavel, thank you

**Pull request merged**
